language: python
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install  -r requirements.txt
script:
- py.test
addons:
  sauce_connect: true
env:
  global:
  - secure: jpBgxTbFB/YEGp8dLfyfB+SvTWa981lEHCpkCyJODJmSPOfdfLdQzP/eVErM+Qp5tk57wu7Pnks5mkQou4zyHarnyVxy8pC5sysSx2le2gJ1EqcsuwPAifwVdOFEum7ChsiLKECAWrOJYw8m12CYCPsF5LrFl6X1RfYOqSo3PXNddVyZ8TrSRO811hz2oT6937YRV5NDxIYU+KDL/hpHiCc6bznAm6VFTg8cwiYAQKjxhJqwtExB51ifZmb/Dy13ufazg4RTUMtTuIIrOToZaU+RPMX7B3PtpdJ6TbM2PvwEArAYB7GLSohQBmlshvi8V9cuSr7nS+Rcd1tFmtpk+OK76n2dNU3nAnkUj5yKcXWoEIjYXl7/9LOCphClGHJC7HruERcclwKCdyvXxuRcYo2hsjJ3alvj5oXpijTVKpoQmkq/H23EbdsEQ5N2Bc5VLCqwFejl57lsVpcgKGBDYwjIH6Eh3/tH+38dWODwkm7nFvCxWqekEcVY5KLqxTddE7MYOphZ/mO180BpOhJ1lGdVGfJEHekurdGBg8o+mHI5oMBRip0rDXv30jOKlPwvf3O8XvaWn2Xx2mZv3NrikyGnPp/jHpArWZldre7YwaogWn+FKwciz5RYhODD4R5/11TvHTcKGn+MXXe5zAA7hA/Cql0suJIUzziKsE5yxnY=
  - secure: CevQAS+ee06GflQde5aAgCOHX7W7R4rneMHpmXkU8xg0ukWOvvbsmAcSv8dsKxqHnCesldPOVSrcCC1zOnKY+Zm1zplGKPlUe+Jq6RwViOgrEwNGFvgXR5+zEQ0fpFp7xHWFUXn+RxAz2qoUGWHmS0nApUVwfNu8j9ja4SrFJu63KqAgvfXhv5Qb5pLkbQRk6MMrdsrvFgOStqdL13pWp/3tHFwAxipy7JeNXUekzGRorVvJEr4LCY9g/AfP0Hm3QcxrgOMgMbyF3+5X6qiizD9tk389wnDL5ZfWrTR639K8/Y5yVRrPmqWYUokC7fsDB4OCDb/lh5ZybnfWz8yRoHcio4ocyl+2nhaCz8Z9FFG1XTMsEc/YW3uFj0GU2W/5gYMh6siWI6DpaB4GcurrvkuPZ5pLL4q+ixEgzq5mVPN5DItlaxdr8yR2s75RZcMTAyVRPdXStG4pXlJ0Zi9DD0eo1ZmjJawufGXgNJkgVtuFZ2WVdrUTpxEQ47EKKAvwxWm5TB25LAUNNJu7eQmG5T6fPQCPmL3VmRzqXyCBKi9fQU5VtPNpqGQE4XjAsvbaYknO+azV2/d9dkNmXRBm0y1w3yOwGKMdkkmmF3xKfwnohjYVl3WoBhB3e6FLaWRAkN89XOF2MK2EHjzrsa83ABUX9FSnaLdgQWvFu6M8vn8=
